[features]
seeds = false
[programs.localnet]
solana_assignment = "EE3g9Y5MsBs9HWoenTvp8SCYv9gGxeiNNjggLt4kzACL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/vpatsenko/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
